Dossiers to review page
JamesPartsafas/ConcordiaCurriculumManager pull request #303
Opened 2024-01-10 20:48 UTC by Dinferno-lol

Includes temporary Dossier Report page, to be replaced later by whoever is working on actual dossier report page.

closes #291

2024-01-10 23:40 UTC, JamesPartsafas requested changes
It seems the buttons on the dossiers to review page don't actually link anywhere (they're there but don't do anything when clicked). 

Also, I may not have mentioned this originally, but since you'll have to go back to make the aforementioned fix anyways, on the my dossiers page, can you also add the button to view the dossier review to the tables for the inReview, approved, and rejected tables?

2024-01-11 01:27 UTC, Dinferno-lol commented
> It seems the buttons on the dossiers to review page don't actually link anywhere (they're there but don't do anything when clicked).
> 
> Also, I may not have mentioned this originally, but since you'll have to go back to make the aforementioned fix anyways, on the my dossiers page, can you also add the button to view the dossier review to the inReview, approved, and rejected tables?

Found the issue, setSelected Dossier wasn't set for that page, thanks for the heads up

2024-01-11 17:52 UTC, JamesPartsafas requested changes
For under review, approved, and rejected, the button to go to the review page doesn't work.

For dossiers requiring your review, the dossier report button doesn't work.

2024-01-16 21:31 UTC, JamesPartsafas approved these changes

2024-01-16 21:32 UTC, merged